# Inventory gerado automaticamente pelo Terraform - NÃO editar à mão.
# (regenerado a cada `terraform apply`)

[server]
54.152.108.122 private_ip=172.31.42.133

[agents]
54.237.23.129
54.197.70.197
54.224.105.113

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/cllone
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
control_plane_private_ip=172.31.42.133
control_plane_public_ip=54.152.108.122
